// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnmjyZ33fzE8SHRSlJG8uH32MT9ej1OE8',
    appId: '1:690075272845:web:8d5afa676a982013c104c4',
    messagingSenderId: '690075272845',
    projectId: 'flutter-ai-app-51d8b',
    authDomain: 'flutter-ai-app-51d8b.firebaseapp.com',
    storageBucket: 'flutter-ai-app-51d8b.firebasestorage.app',
    measurementId: 'G-VCK2GQYVFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvWQ2adawMJ-VFUgKjmeemyGSoen5qTo',
    appId: '1:690075272845:android:9da8b3bd53773032c104c4',
    messagingSenderId: '690075272845',
    projectId: 'flutter-ai-app-51d8b',
    storageBucket: 'flutter-ai-app-51d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vn3EtPYnA8ynkJiFBzI5SzhMVpHw6V8',
    appId: '1:690075272845:ios:99806fe0a6c3f824c104c4',
    messagingSenderId: '690075272845',
    projectId: 'flutter-ai-app-51d8b',
    storageBucket: 'flutter-ai-app-51d8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5vn3EtPYnA8ynkJiFBzI5SzhMVpHw6V8',
    appId: '1:690075272845:ios:99806fe0a6c3f824c104c4',
    messagingSenderId: '690075272845',
    projectId: 'flutter-ai-app-51d8b',
    storageBucket: 'flutter-ai-app-51d8b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnmjyZ33fzE8SHRSlJG8uH32MT9ej1OE8',
    appId: '1:690075272845:web:8a552b0adad92183c104c4',
    messagingSenderId: '690075272845',
    projectId: 'flutter-ai-app-51d8b',
    authDomain: 'flutter-ai-app-51d8b.firebaseapp.com',
    storageBucket: 'flutter-ai-app-51d8b.firebasestorage.app',
    measurementId: 'G-LBJSP6BCE7',
  );
}
