import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_ai_app/pages/account_screen.dart';
import 'package:flutter_ai_app/pages/login_screen.dart';
import 'package:flutter_ai_app/pages/signup_screen.dart';
import 'package:flutter_ai_app/providers/account_provider.dart';
import 'package:flutter_ai_app/providers/login_provider.dart';
import 'package:flutter_ai_app/providers/signup_provider.dart';
import 'package:flutter_ai_app/utils/app_shared_preference.dart';
import 'package:provider/provider.dart';
import 'pages/recipe_generator.dart';
import 'firebase_options.dart';
import 'pages/image_generator.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await AppSharedPreference.init();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AccountProvider()),
        ChangeNotifierProvider(create: (_) => LoginProvider()),
        ChangeNotifierProvider(create: (_) => SignupProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Friendly Meals',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: AppSharedPreference.getLoggedIn() ? '/home' : '/',
      routes: {
        '/': (context) => const AccountScreen(),
        '/home': (context) => const RecipeGeneratorScreen(),
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
      },
    );
  }
}
